// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yextfzthlcwtnfglxacw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlleHRmenRobGN3dG5mZ2x4YWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjczOTgsImV4cCI6MjA2NDY0MzM5OH0.PRB1T54djnA0kkEmrhFkCwo8TvhiAvYnyai28SxPQTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);